
#CC=gcc
DAEMON_PREFIX=rs232-daemon-mfd
PORT_NUMBER_PREFIX=rs232Number
PORT_TABLE_PREFIX=rs232PortTable
ASYNCPORT_TABLE_PREFIX=rs232AsyncPortTable

NETSNMPCONFIG=net-snmp-config


# uncomment this if you have GNU make
#NETSNMPCFLAGS := $(shell $(NETSNMPCONFIG) --base-cflags)
#NETSNMPLIBS := $(shell $(NETSNMPCONFIG) --agent-libs)
NETSNMPCFLAGS=`$(NETSNMPCONFIG) --base-cflags`
NETSNMPLIBS=`$(NETSNMPCONFIG) --agent-libs`

LIBS=$(NETSNMPLIBS)


STRICT_FLAGS = -Wall -Wstrict-prototypes
CFLAGS=-I. $(NETSNMPCFLAGS) $(STRICT_FLAGS)


USER_OBJS =  \
	$(PORT_TABLE_PREFIX)/$(PORT_TABLE_PREFIX)_data_get.o \
	$(PORT_TABLE_PREFIX)/$(PORT_TABLE_PREFIX)_data_set.o \
	$(PORT_TABLE_PREFIX)/$(PORT_TABLE_PREFIX)_data_access.o \
	$(ASYNCPORT_TABLE_PREFIX)/$(ASYNCPORT_TABLE_PREFIX)_data_get.o \
	$(ASYNCPORT_TABLE_PREFIX)/$(ASYNCPORT_TABLE_PREFIX)_data_set.o \
	$(ASYNCPORT_TABLE_PREFIX)/$(ASYNCPORT_TABLE_PREFIX)_data_access.o

OBJS =  $(USER_OBJS) \
	$(PORT_TABLE_PREFIX)/$(PORT_TABLE_PREFIX).o \
	$(ASYNCPORT_TABLE_PREFIX)/$(ASYNCPORT_TABLE_PREFIX).o \
	$(PORT_NUMBER_PREFIX)/$(PORT_NUMBER_PREFIX).o \
	$(PORT_TABLE_PREFIX)/$(PORT_TABLE_PREFIX)_interface.o \
	$(ASYNCPORT_TABLE_PREFIX)/$(ASYNCPORT_TABLE_PREFIX)_interface.o \
	rs232_subagent.o

TARGETS=$(DAEMON_PREFIX)

.SUFFIXES:
.SUFFIXES: .c .o .deps


all: $(TARGETS)

user: $(USER_OBJS)

$(TARGETS): $(LIB_DEPS)

$(DAEMON_PREFIX): $(OBJS) 
	$(CC) -o $(DAEMON_PREFIX) $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) $(TARGETS)

