/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "rs232PortTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "rs232PortTable_interface.h"

netsnmp_feature_require(baby_steps)
netsnmp_feature_require(row_merge)
netsnmp_feature_require(check_all_requests_error)

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232PortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232PortTable is subid 2 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.2, length: 9
*/
typedef struct rs232PortTable_interface_ctx_s {

   netsnmp_container              *container;

   rs232PortTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

    u_int                             table_dirty;

} rs232PortTable_interface_ctx;

static rs232PortTable_interface_ctx rs232PortTable_if_ctx;

static void _rs232PortTable_container_init(
    rs232PortTable_interface_ctx *if_ctx);
static void _rs232PortTable_container_shutdown(
    rs232PortTable_interface_ctx *if_ctx);


netsnmp_container *
rs232PortTable_container_get( void )
{
    return rs232PortTable_if_ctx.container;
}

rs232PortTable_registration *
rs232PortTable_registration_get( void )
{
    return rs232PortTable_if_ctx.user_ctx;
}

rs232PortTable_registration *
rs232PortTable_registration_set( rs232PortTable_registration * newreg )
{
    rs232PortTable_registration * old = rs232PortTable_if_ctx.user_ctx;
    rs232PortTable_if_ctx.user_ctx = newreg;
    return old;
}

int
rs232PortTable_container_size( void )
{
    return CONTAINER_SIZE(rs232PortTable_if_ctx.container);
}

u_int
rs232PortTable_dirty_get( void )
{
    return rs232PortTable_if_ctx.table_dirty;
}

void
rs232PortTable_dirty_set( u_int status )
{
    DEBUGMSGTL(("rs232PortTable:rs232PortTable_dirty_set",
                "called. was %d, now %d\n",
                rs232PortTable_if_ctx.table_dirty, status));
    rs232PortTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_rs232PortTable_pre_request;
static Netsnmp_Node_Handler _mfd_rs232PortTable_post_request;
static Netsnmp_Node_Handler _mfd_rs232PortTable_object_lookup;
static Netsnmp_Node_Handler _mfd_rs232PortTable_get_values;
static Netsnmp_Node_Handler _mfd_rs232PortTable_check_objects;
static Netsnmp_Node_Handler _mfd_rs232PortTable_undo_setup;
static Netsnmp_Node_Handler _mfd_rs232PortTable_set_values;
static Netsnmp_Node_Handler _mfd_rs232PortTable_undo_cleanup;
static Netsnmp_Node_Handler _mfd_rs232PortTable_undo_values;
static Netsnmp_Node_Handler _mfd_rs232PortTable_commit;
static Netsnmp_Node_Handler _mfd_rs232PortTable_undo_commit;
static Netsnmp_Node_Handler _mfd_rs232PortTable_irreversible_commit;

rs232PortTable_data *rs232PortTable_allocate_data(void);

/**
 * @internal
 * Initialize the table rs232PortTable 
 *    (Define its contents and how it's structured)
 */
void
_rs232PortTable_initialize_interface(rs232PortTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &rs232PortTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &rs232PortTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for rs232PortTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: rs232PortIndex */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = RS232PORTTABLE_MIN_COL;
    tbl_info->max_column = RS232PORTTABLE_MAX_COL;

    /*
     * save users context
     */
    rs232PortTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    rs232PortTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _rs232PortTable_container_init(&rs232PortTable_if_ctx);
    if (NULL == rs232PortTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for rs232PortTable\n");
        return;
    }

    //rachel
    rs232PortTable_container_load(rs232PortTable_if_ctx.container);
    //rachel
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_rs232PortTable_object_lookup;
    access_multiplexer->get_values = _mfd_rs232PortTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_rs232PortTable_pre_request;
    access_multiplexer->post_request = _mfd_rs232PortTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_rs232PortTable_check_objects;
    access_multiplexer->undo_setup = _mfd_rs232PortTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_rs232PortTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_rs232PortTable_set_values;
    access_multiplexer->undo_sets = _mfd_rs232PortTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_rs232PortTable_commit;
    access_multiplexer->undo_commit = _mfd_rs232PortTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_rs232PortTable_irreversible_commit;
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("rs232PortTable:init_rs232PortTable",
                "Registering rs232PortTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("rs232PortTable", handler,
                                                  rs232PortTable_oid,
                                                  rs232PortTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if (defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))         //rachel
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RWRITE
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table rs232PortTable\n");
        return;
    }
    reginfo->my_reg_void = &rs232PortTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            rs232PortTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _rs232PortTable_initialize_interface */

/**
 * @internal
 * Shutdown the table rs232PortTable
 */
void
_rs232PortTable_shutdown_interface(rs232PortTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _rs232PortTable_container_shutdown(&rs232PortTable_if_ctx);
}

void
rs232PortTable_valid_columns_set(netsnmp_column_info *vc)
{
    rs232PortTable_if_ctx.tbl_info.valid_columns = vc;
} /* rs232PortTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
rs232PortTable_index_to_oid(netsnmp_index *oid_idx,
                         rs232PortTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * rs232PortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
     */
    netsnmp_variable_list var_rs232PortIndex;

    /*
     * set up varbinds
     */
    memset( &var_rs232PortIndex, 0x00, sizeof(var_rs232PortIndex) );
    var_rs232PortIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_rs232PortIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_index_to_oid","called\n"));

        /* rs232PortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H */
    snmp_set_var_value(&var_rs232PortIndex, &mib_idx->rs232PortIndex, sizeof(mib_idx->rs232PortIndex));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_rs232PortIndex);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_rs232PortIndex );

    return err;
} /* rs232PortTable_index_to_oid */

/**
 * extract rs232PortTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
rs232PortTable_index_from_oid(netsnmp_index *oid_idx,
                         rs232PortTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * rs232PortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
     */
    netsnmp_variable_list var_rs232PortIndex;

    /*
     * set up varbinds
     */
    memset( &var_rs232PortIndex, 0x00, sizeof(var_rs232PortIndex) );
    var_rs232PortIndex.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_rs232PortIndex.next_variable =  NULL;


    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_rs232PortIndex );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->rs232PortIndex = *((long *)var_rs232PortIndex.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_rs232PortIndex );

    return err;
} /* rs232PortTable_index_from_oid */


/*
 * rs232PortTable_allocate_data
 *
 * Purpose: create new rs232PortTable_data.
 */
rs232PortTable_data *
rs232PortTable_allocate_data(void)
{
    rs232PortTable_data *rtn = SNMP_MALLOC_TYPEDEF(rs232PortTable_data);

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_allocate_data","called\n"));

    if(NULL == rtn) {
        snmp_log(LOG_ERR, "unable to malloc memory for new "
                 "rs232PortTable_data.\n");
    }

    return rtn;
} /* rs232PortTable_allocate_data */

/*
 * rs232PortTable_release_data
 *
 * Purpose: release rs232PortTable data.
 */
void
rs232PortTable_release_data(rs232PortTable_data *data)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_release_data","called\n"));

    free(data);
} /* rs232PortTable_release_data */

/* *********************************************************************
 * @internal
 * allocate resources for a rs232PortTable_rowreq_ctx
 */
rs232PortTable_rowreq_ctx *
rs232PortTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(rs232PortTable_rowreq_ctx);

    DEBUGMSGTL(("internal:rs232PortTable:rs232PortTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "rs232PortTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->rs232PortTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            rs232PortTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           rs232PortTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* rs232PortTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a rs232PortTable_rowreq_ctx
 */
void
rs232PortTable_release_rowreq_ctx(rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:rs232PortTable:rs232PortTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rs232PortTable_rowreq_ctx_cleanup(rowreq_ctx);

    if(rowreq_ctx->undo)
        rs232PortTable_release_data(rowreq_ctx->undo);
 
    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* rs232PortTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rs232PortTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:rs232PortTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = rs232PortTable_pre_request(rs232PortTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rs232PortTable","error %d from "
                    "rs232PortTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rs232PortTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        rs232PortTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:rs232PortTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    if ((MFD_SUCCESS != packet_rc) && rs232PortTable_dirty_get()) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        snmp_log(LOG_WARNING, "rs232PortTable dirty flag set in post_request "
                 "but status != SUCCESS.\n");
    }

    rc = rs232PortTable_post_request(rs232PortTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rs232PortTable","error %d from "
                    "rs232PortTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_rs232PortTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * rs232PortTable_interface_ctx *if_ctx =
     *             (rs232PortTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        rs232PortTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_rs232PortTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_rs232PortTable_get_column( rs232PortTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* (INDEX) rs232PortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H */
    case COLUMN_RS232PORTINDEX:
        //rachel
        rc = MFD_SKIP;
        //rachel
        break;

    /* rs232PortType(2)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_RS232PORTTYPE:
        //rachel
        rc = MFD_SKIP;
        //rachel
        break;

    /* rs232PortInSigNumber(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_RS232PORTINSIGNUMBER:
        //rachel
        rc = MFD_SKIP;
        //rachel
        break;

    /* rs232PortOutSigNumber(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_RS232PORTOUTSIGNUMBER:
        //rachel
        rc = MFD_SKIP;
        //rachel
        break;

    /* rs232PortInSpeed(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTINSPEED:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = rs232PortInSpeed_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* rs232PortOutSpeed(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTOUTSPEED:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = rs232PortOutSpeed_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* rs232PortInFlowType(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTINFLOWTYPE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = rs232PortInFlowType_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* rs232PortOutFlowType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTOUTFLOWTYPE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = rs232PortOutFlowType_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (RS232PORTTABLE_MIN_COL <= column && column <= RS232PORTTABLE_MAX_COL) {
            DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _rs232PortTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _rs232PortTable_get_column */

int
_mfd_rs232PortTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _rs232PortTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
NETSNMP_STATIC_INLINE int
_rs232PortTable_check_column( rs232PortTable_rowreq_ctx *rowreq_ctx,
                         netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_check_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {
    /* (INDEX) rs232PortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H */
    case COLUMN_RS232PORTINDEX:
        rc = SNMP_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /* rs232PortType(2)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_RS232PORTTYPE:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* rs232PortInSigNumber(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_RS232PORTINSIGNUMBER:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* rs232PortOutSigNumber(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_RS232PORTOUTSIGNUMBER:
        rc = SNMP_ERR_NOTWRITABLE;
        break;

    /* rs232PortInSpeed(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTINSPEED:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.rs232PortInSpeed ) );
    //rachel
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
        && ( *var->val.integer != RS232PORTINSPEED_BD300 )
        && ( *var->val.integer != RS232PORTINSPEED_BD600 )
        && ( *var->val.integer != RS232PORTINSPEED_BD1200 )
        && ( *var->val.integer != RS232PORTINSPEED_BD2400 )
        && ( *var->val.integer != RS232PORTINSPEED_BD4800 )
        && ( *var->val.integer != RS232PORTINSPEED_BD9600 )
        && ( *var->val.integer != RS232PORTINSPEED_BD19200 )
        && ( *var->val.integer != RS232PORTINSPEED_BD38400 )
        && ( *var->val.integer != RS232PORTINSPEED_BD57600 )
        && ( *var->val.integer != RS232PORTINSPEED_BD115200 )
        && ( *var->val.integer != RS232PORTINSPEED_BD230400 )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    //rachel
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("rs232PortTable:_rs232PortTable_check_column:rs232PortInSpeed",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = rs232PortInSpeed_check_value( rowreq_ctx, *((long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from rs232PortInSpeed_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* rs232PortOutSpeed(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTOUTSPEED:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.rs232PortOutSpeed ) );
    //rachel
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
        && ( *var->val.integer != RS232PORTOUTSPEED_BD300 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD600 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD1200 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD2400 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD4800 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD9600 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD19200 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD38400 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD57600 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD115200 )
        && ( *var->val.integer != RS232PORTOUTSPEED_BD230400 )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    //rachel
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("rs232PortTable:_rs232PortTable_check_column:rs232PortOutSpeed",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = rs232PortOutSpeed_check_value( rowreq_ctx, *((long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from rs232PortOutSpeed_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* rs232PortInFlowType(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTINFLOWTYPE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.rs232PortInFlowType ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
        && ( *var->val.integer != RS232PORTINFLOWTYPE_NONE )
        && ( *var->val.integer != RS232PORTINFLOWTYPE_CTSRTS )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("rs232PortTable:_rs232PortTable_check_column:rs232PortInFlowType",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = rs232PortInFlowType_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from rs232PortInFlowType_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

    /* rs232PortOutFlowType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTOUTFLOWTYPE:
    rc = netsnmp_check_vb_type_and_size( var, ASN_INTEGER,
        sizeof( rowreq_ctx->data.rs232PortOutFlowType ) );
    /* check that the value is one of defined enums */
    if( (SNMPERR_SUCCESS == rc)
        && ( *var->val.integer != RS232PORTOUTFLOWTYPE_NONE )
        && ( *var->val.integer != RS232PORTOUTFLOWTYPE_CTSRTS )
        ) {
        rc = SNMP_ERR_WRONGVALUE;
        }
    if(SNMPERR_SUCCESS != rc) {
        DEBUGMSGTL(("rs232PortTable:_rs232PortTable_check_column:rs232PortOutFlowType",
                    "varbind validation failed (eg bad type or size)\n"));
    }
    else {
        rc = rs232PortOutFlowType_check_value( rowreq_ctx, *((u_long *)var->val.string) );
        if((MFD_SUCCESS != rc) && (MFD_NOT_VALID_EVER != rc) &&
           (MFD_NOT_VALID_NOW != rc)) {
            snmp_log(LOG_ERR, "bad rc %d from rs232PortOutFlowType_check_value\n", rc);
            rc = SNMP_ERR_GENERR;
        }
    }
        break;

        default: /** We shouldn't get here */
            rc = SNMP_ERR_GENERR;
            snmp_log(LOG_ERR, "unknown column %d in _rs232PortTable_check_column\n", column);
    }

    return rc;
} /* _rs232PortTable_check_column */

int
_mfd_rs232PortTable_check_objects(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_check_objects","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {

        /*
         * get column number from table request info, and check that column
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;

        rc = _rs232PortTable_check_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));
            break;
        }

    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_check_objects */


/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_rs232PortTable_undo_setup_column( rs232PortTable_rowreq_ctx *rowreq_ctx, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_undo_setup_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* rs232PortInSpeed(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTINSPEED:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINSPEED_FLAG;
        rc = rs232PortInSpeed_undo_setup(rowreq_ctx );
        break;

    /* rs232PortOutSpeed(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTOUTSPEED:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTSPEED_FLAG;
        rc = rs232PortOutSpeed_undo_setup(rowreq_ctx );
        break;

    /* rs232PortInFlowType(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTINFLOWTYPE:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINFLOWTYPE_FLAG;
        rc = rs232PortInFlowType_undo_setup(rowreq_ctx );
        break;

    /* rs232PortOutFlowType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTOUTFLOWTYPE:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTFLOWTYPE_FLAG;
        rc = rs232PortOutFlowType_undo_setup(rowreq_ctx );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _rs232PortTable_undo_setup_column\n", column);
         break;
    }

    return rc;
} /* _rs232PortTable_undo_setup_column */


/**
 * @internal
 * undo setup
 */
int
_mfd_rs232PortTable_undo_setup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_undo_setup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = rs232PortTable_allocate_data();
    if(NULL == rowreq_ctx->undo) {
        /** msg already logged */
        netsnmp_request_set_error_all(requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        return SNMP_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = rs232PortTable_undo_setup(rowreq_ctx);
    if (MFD_SUCCESS != rc)  {
        DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                    "rs232PortTable_undo_setup\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    else {
        /*
         * column undo setup
         */
        netsnmp_table_request_info * tri;
        for(;requests; requests = requests->next) {
            /*
             * set column data
             */
            tri = netsnmp_extract_table_info(requests);
            if(NULL == tri)
                continue;
            
            rc = _rs232PortTable_undo_setup_column(rowreq_ctx, tri->colnum);
            if(MFD_SUCCESS != rc)  {
                DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                            "rs232PortTable_undo_setup_column\n", rc));
                netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
            }
        } /* for results */
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int
_mfd_rs232PortTable_undo_cleanup(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_undo_cleanup","called\n"));

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if (NULL == rowreq_ctx)
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = rs232PortTable_undo_cleanup(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                    "rs232PortTable_undo_cleanup\n", rc));
    }

    /*
     * release undo context, if needed
     */
    if(rowreq_ctx->undo) {
         rs232PortTable_release_data(rowreq_ctx->undo);
         rowreq_ctx->undo = NULL;
    }


    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_rs232PortTable_set_column( rs232PortTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_set_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* rs232PortInSpeed(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTINSPEED:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINSPEED_FLAG;
        rc = rs232PortInSpeed_set(rowreq_ctx, *((long *)var->val.string) );
        break;

    /* rs232PortOutSpeed(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTOUTSPEED:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTSPEED_FLAG;
        rc = rs232PortOutSpeed_set(rowreq_ctx, *((long *)var->val.string) );
        break;

    /* rs232PortInFlowType(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTINFLOWTYPE:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINFLOWTYPE_FLAG;
        rc = rs232PortInFlowType_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

    /* rs232PortOutFlowType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTOUTFLOWTYPE:
        rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTFLOWTYPE_FLAG;
        rc = rs232PortOutFlowType_set(rowreq_ctx, *((u_long *)var->val.string) );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _rs232PortTable_set_column\n", column);
         rc = SNMP_ERR_GENERR;
         break;
    }
    
    return rc;
} /* _rs232PortTable_set_column */

int
_mfd_rs232PortTable_set_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    int                          rc = SNMP_ERR_NOERROR;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_set_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rowreq_ctx->column_set_flags = 0;
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _rs232PortTable_set_column(rowreq_ctx,
                                    requests->requestvb, tri->colnum);
        if(MFD_SUCCESS != rc)  {
            DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                        "rs232PortTable_set_column\n", rc));
            netsnmp_set_request_error(agtreq_info, requests, SNMP_VALIDATE_ERR(rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int
_mfd_rs232PortTable_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = rs232PortTable_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                    "rs232PortTable_commit\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        rs232PortTable_dirty_set( rs232PortTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return SNMP_ERR_NOERROR;
}

int
_mfd_rs232PortTable_undo_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_undo_commit","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        u_int  d = rs232PortTable_dirty_get();

        netsnmp_assert(d != 0);
        if(d)
            rs232PortTable_dirty_set( d - 1 );
    }

    rc = rs232PortTable_undo_commit(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                    "rs232PortTable_undo_commit\n", rc));
    }

    if (rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY) {
        snmp_log(LOG_WARNING, "rs232PortTable row dirty flag still set after undo_commit\n");
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_rs232PortTable_undo_column( rs232PortTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_undo_column",
                "called for %d\n", column));

    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* rs232PortInSpeed(5)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTINSPEED:
        rc = rs232PortInSpeed_undo(rowreq_ctx);
        break;

    /* rs232PortOutSpeed(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    case COLUMN_RS232PORTOUTSPEED:
        rc = rs232PortOutSpeed_undo(rowreq_ctx);
        break;

    /* rs232PortInFlowType(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTINFLOWTYPE:
        rc = rs232PortInFlowType_undo(rowreq_ctx);
        break;

    /* rs232PortOutFlowType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h */
    case COLUMN_RS232PORTOUTFLOWTYPE:
        rc = rs232PortOutFlowType_undo(rowreq_ctx);
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _rs232PortTable_undo_column\n", column);
         break;
    }

    return rc;
} /* _rs232PortTable_undo_column */

int
_mfd_rs232PortTable_undo_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc;
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;

    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_undo_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    rc = rs232PortTable_undo(rowreq_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                    "rs232PortTable_undo\n", rc));
    }
    
    for(;requests; requests = requests->next) {
        /*
         * set column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _rs232PortTable_undo_column(rowreq_ctx, requests->requestvb,
                                     tri->colnum);
        if (MFD_SUCCESS != rc) {
            /*
             * nothing we can do about it but log it
             */
            DEBUGMSGTL(("rs232PortTable:mfd","error %d from "
                        "rs232PortTable_undo_column\n", rc));
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int
_mfd_rs232PortTable_irreversible_commit(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    rs232PortTable_rowreq_ctx *rowreq_ctx = (rs232PortTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:rs232PortTable:_mfd_rs232PortTable_irreversible:commit","called\n"));
   
    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
        if (! (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED))
            CONTAINER_REMOVE(rs232PortTable_if_ctx.container, rowreq_ctx);
    }
    else {
        if (rowreq_ctx->column_set_flags) {
           rowreq_ctx->column_set_flags = 0;
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_rs232PortTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static void
_container_item_free(rs232PortTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:rs232PortTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    rs232PortTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:rs232PortTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in rs232PortTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    rs232PortTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_rs232PortTable_container_init(rs232PortTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_container_init","called\n"));

    /*
     * container init
     */    
    rs232PortTable_container_init(&if_ctx->container);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("rs232PortTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "rs232PortTable_container_init\n");
        return;
    }

} /* _rs232PortTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_rs232PortTable_container_shutdown(rs232PortTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:rs232PortTable:_rs232PortTable_container_shutdown","called\n"));

    rs232PortTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _rs232PortTable_container_shutdown */


rs232PortTable_rowreq_ctx *
rs232PortTable_row_find_by_mib_index(rs232PortTable_mib_index *mib_idx)
{
    rs232PortTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = rs232PortTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (rs232PortTable_rowreq_ctx*)CONTAINER_FIND(rs232PortTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

