/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file rs232PortTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef RS232PORTTABLE_DATA_GET_H
#define RS232PORTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232PortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232PortTable is subid 2 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.2, length: 9
*/
    /*
     * indexes
     */

    int rs232PortType_get( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long * rs232PortType_val_ptr );
    int rs232PortInSigNumber_get( rs232PortTable_rowreq_ctx *rowreq_ctx, long * rs232PortInSigNumber_val_ptr );
    int rs232PortOutSigNumber_get( rs232PortTable_rowreq_ctx *rowreq_ctx, long * rs232PortOutSigNumber_val_ptr );
    int rs232PortInSpeed_get( rs232PortTable_rowreq_ctx *rowreq_ctx, long * rs232PortInSpeed_val_ptr );
    int rs232PortOutSpeed_get( rs232PortTable_rowreq_ctx *rowreq_ctx, long * rs232PortOutSpeed_val_ptr );
    int rs232PortInFlowType_get( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long * rs232PortInFlowType_val_ptr );
    int rs232PortOutFlowType_get( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long * rs232PortOutFlowType_val_ptr );


int rs232PortTable_indexes_set_tbl_idx(rs232PortTable_mib_index *tbl_idx, long rs232PortIndex_val);
int rs232PortTable_indexes_set(rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* RS232PORTTABLE_DATA_GET_H */
/** @} */
