/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef RS232PORTTABLE_DATA_SET_H
#define RS232PORTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232PortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232PortTable is subid 2 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.2, length: 9
*/


int rs232PortTable_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx);
int rs232PortTable_undo_cleanup( rs232PortTable_rowreq_ctx *rowreq_ctx);
int rs232PortTable_undo( rs232PortTable_rowreq_ctx *rowreq_ctx);
int rs232PortTable_commit( rs232PortTable_rowreq_ctx *rowreq_ctx);
int rs232PortTable_undo_commit( rs232PortTable_rowreq_ctx *rowreq_ctx);


int rs232PortType_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortType_val);
int rs232PortType_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortType_set( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortType_val );
int rs232PortType_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortInSigNumber_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSigNumber_val);
int rs232PortInSigNumber_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortInSigNumber_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSigNumber_val );
int rs232PortInSigNumber_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortOutSigNumber_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSigNumber_val);
int rs232PortOutSigNumber_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortOutSigNumber_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSigNumber_val );
int rs232PortOutSigNumber_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortInSpeed_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSpeed_val);
int rs232PortInSpeed_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortInSpeed_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSpeed_val );
int rs232PortInSpeed_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortOutSpeed_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSpeed_val);
int rs232PortOutSpeed_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortOutSpeed_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSpeed_val );
int rs232PortOutSpeed_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortInFlowType_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortInFlowType_val);
int rs232PortInFlowType_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortInFlowType_set( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortInFlowType_val );
int rs232PortInFlowType_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );

int rs232PortOutFlowType_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortOutFlowType_val);
int rs232PortOutFlowType_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx );
int rs232PortOutFlowType_set( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortOutFlowType_val );
int rs232PortOutFlowType_undo( rs232PortTable_rowreq_ctx *rowreq_ctx );


int rs232PortTable_check_dependencies(rs232PortTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* RS232PORTTABLE_DATA_SET_H */
