/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "rs232PortTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232PortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232PortTable is subid 2 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.2, length: 9
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * rs232PortTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * rs232PortTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
rs232PortTable_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup rs232PortTable undo.
     * set up rs232PortTable undo information, in preparation for a set.
     * Undo storage is in (* rs232PortOutFlowType_val_ptr )*
     */

    return rc;
} /* rs232PortTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
rs232PortTable_undo( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> rs232PortTable undo.
     * rs232PortTable undo information, in response to a failed set.
     * Undo storage is in (* rs232PortOutFlowType_val_ptr )*
     */

    return rc;
} /* rs232PortTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rs232PortTable_undo_cleanup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup rs232PortTable undo.
     * Undo storage is in (* rs232PortOutFlowType_val_ptr )*
     */

    return rc;
} /* rs232PortTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * rs232PortTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param rs232PortTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rs232PortTable_commit( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit rs232PortTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_RS232PORTINSPEED_FLAG) {
       save_flags &= ~COLUMN_RS232PORTINSPEED_FLAG; /* clear rs232PortInSpeed */
       //rachel
       rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINSPEED_FLAG;
       //rachel
    }

    if (save_flags & COLUMN_RS232PORTOUTSPEED_FLAG) {
       save_flags &= ~COLUMN_RS232PORTOUTSPEED_FLAG; /* clear rs232PortOutSpeed */
       //rachel
       rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTSPEED_FLAG;
       //rachel
    }

    if (save_flags & COLUMN_RS232PORTINFLOWTYPE_FLAG) {
       save_flags &= ~COLUMN_RS232PORTINFLOWTYPE_FLAG; /* clear rs232PortInFlowType */
       //rachel
       rowreq_ctx->column_set_flags |= COLUMN_RS232PORTINFLOWTYPE_FLAG;
       //rachel
    }

    if (save_flags & COLUMN_RS232PORTOUTFLOWTYPE_FLAG) {
       save_flags &= ~COLUMN_RS232PORTOUTFLOWTYPE_FLAG; /* clear rs232PortOutFlowType */
       //rachel
       rowreq_ctx->column_set_flags |= COLUMN_RS232PORTOUTFLOWTYPE_FLAG;
       //rachel
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* rs232PortTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * rs232PortTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param rs232PortTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rs232PortTable_undo_commit( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo rs232PortTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* rs232PortTable_undo_commit */

/*
 * TODO:440:M: Implement rs232PortTable node value checks.
 * TODO:450:M: Implement rs232PortTable undo functions.
 * TODO:460:M: Implement rs232PortTable set functions.
 * TODO:480:M: Implement rs232PortTable commit functions.
 */
/*---------------------------------------------------------------------
 * RS-232-MIB::rs232PortEntry.rs232PortInSpeed
 * rs232PortInSpeed is subid 5 of rs232PortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.10.33.2.1.5
 * Description:
The port's input speed in bits per second.  Note that
        non-standard values, such as 9612, are probably not allowed
        on most implementations.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rs232PortInSpeed_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rs232PortTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rs232PortInSpeed_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSpeed_val)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInSpeed_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rs232PortInSpeed value.
     */

    return MFD_SUCCESS; /* rs232PortInSpeed value not illegal */
} /* rs232PortInSpeed_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rs232PortTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rs232PortInSpeed_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInSpeed_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rs232PortInSpeed undo.
     */
    /*
     * copy rs232PortInSpeed data
     * set rowreq_ctx->undo->rs232PortInSpeed from rowreq_ctx->data.rs232PortInSpeed
     */
    rowreq_ctx->undo->rs232PortInSpeed = rowreq_ctx->data.rs232PortInSpeed;


    return MFD_SUCCESS;
} /* rs232PortInSpeed_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rs232PortInSpeed_val
 *        A long containing the new value.
 */
int
rs232PortInSpeed_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortInSpeed_val )
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInSpeed_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rs232PortInSpeed value.
     * set rs232PortInSpeed value in rowreq_ctx->data
     */
    rowreq_ctx->data.rs232PortInSpeed = rs232PortInSpeed_val;

    return MFD_SUCCESS;
} /* rs232PortInSpeed_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rs232PortInSpeed_undo( rs232PortTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInSpeed_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rs232PortInSpeed undo.
     */
    /*
     * copy rs232PortInSpeed data
     * set rowreq_ctx->data.rs232PortInSpeed from rowreq_ctx->undo->rs232PortInSpeed
     */
    rowreq_ctx->data.rs232PortInSpeed = rowreq_ctx->undo->rs232PortInSpeed;

    
    return MFD_SUCCESS;
} /* rs232PortInSpeed_undo */

/*---------------------------------------------------------------------
 * RS-232-MIB::rs232PortEntry.rs232PortOutSpeed
 * rs232PortOutSpeed is subid 6 of rs232PortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.10.33.2.1.6
 * Description:
The port's output speed in bits per second.  Note that
        non-standard values, such as 9612, are probably not allowed
        on most implementations.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rs232PortOutSpeed_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rs232PortTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rs232PortOutSpeed_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSpeed_val)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutSpeed_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rs232PortOutSpeed value.
     */

    return MFD_SUCCESS; /* rs232PortOutSpeed value not illegal */
} /* rs232PortOutSpeed_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rs232PortTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rs232PortOutSpeed_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutSpeed_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rs232PortOutSpeed undo.
     */
    /*
     * copy rs232PortOutSpeed data
     * set rowreq_ctx->undo->rs232PortOutSpeed from rowreq_ctx->data.rs232PortOutSpeed
     */
    rowreq_ctx->undo->rs232PortOutSpeed = rowreq_ctx->data.rs232PortOutSpeed;


    return MFD_SUCCESS;
} /* rs232PortOutSpeed_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rs232PortOutSpeed_val
 *        A long containing the new value.
 */
int
rs232PortOutSpeed_set( rs232PortTable_rowreq_ctx *rowreq_ctx, long rs232PortOutSpeed_val )
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutSpeed_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rs232PortOutSpeed value.
     * set rs232PortOutSpeed value in rowreq_ctx->data
     */
    rowreq_ctx->data.rs232PortOutSpeed = rs232PortOutSpeed_val;

    return MFD_SUCCESS;
} /* rs232PortOutSpeed_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rs232PortOutSpeed_undo( rs232PortTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutSpeed_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rs232PortOutSpeed undo.
     */
    /*
     * copy rs232PortOutSpeed data
     * set rowreq_ctx->data.rs232PortOutSpeed from rowreq_ctx->undo->rs232PortOutSpeed
     */
    rowreq_ctx->data.rs232PortOutSpeed = rowreq_ctx->undo->rs232PortOutSpeed;

    
    return MFD_SUCCESS;
} /* rs232PortOutSpeed_undo */

/*---------------------------------------------------------------------
 * RS-232-MIB::rs232PortEntry.rs232PortInFlowType
 * rs232PortInFlowType is subid 7 of rs232PortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.10.33.2.1.7
 * Description:
The port's type of input flow control.  'none'
        indicates no flow control at this level.
        'ctsRts' and 'dsrDtr' indicate use of the indicated
        hardware signals.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  none(1), ctsRts(2), dsrDtr(3)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rs232PortInFlowType_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rs232PortTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  none(1), ctsRts(2), dsrDtr(3)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rs232PortInFlowType_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortInFlowType_val)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInFlowType_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rs232PortInFlowType value.
     */

    return MFD_SUCCESS; /* rs232PortInFlowType value not illegal */
} /* rs232PortInFlowType_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rs232PortTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rs232PortInFlowType_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInFlowType_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rs232PortInFlowType undo.
     */
    /*
     * copy rs232PortInFlowType data
     * set rowreq_ctx->undo->rs232PortInFlowType from rowreq_ctx->data.rs232PortInFlowType
     */
    rowreq_ctx->undo->rs232PortInFlowType = rowreq_ctx->data.rs232PortInFlowType;


    return MFD_SUCCESS;
} /* rs232PortInFlowType_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rs232PortInFlowType_val
 *        A long containing the new value.
 */
int
rs232PortInFlowType_set( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortInFlowType_val )
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInFlowType_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rs232PortInFlowType value.
     * set rs232PortInFlowType value in rowreq_ctx->data
     */
    rowreq_ctx->data.rs232PortInFlowType = rs232PortInFlowType_val;

    return MFD_SUCCESS;
} /* rs232PortInFlowType_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rs232PortInFlowType_undo( rs232PortTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortInFlowType_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rs232PortInFlowType undo.
     */
    /*
     * copy rs232PortInFlowType data
     * set rowreq_ctx->data.rs232PortInFlowType from rowreq_ctx->undo->rs232PortInFlowType
     */
    rowreq_ctx->data.rs232PortInFlowType = rowreq_ctx->undo->rs232PortInFlowType;

    
    return MFD_SUCCESS;
} /* rs232PortInFlowType_undo */

/*---------------------------------------------------------------------
 * RS-232-MIB::rs232PortEntry.rs232PortOutFlowType
 * rs232PortOutFlowType is subid 8 of rs232PortEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.2.1.10.33.2.1.8
 * Description:
The port's type of output flow control.  'none'

        indicates no flow control at this level.
        'ctsRts' and 'dsrDtr' indicate use of the indicated
        hardware signals.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  none(1), ctsRts(2), dsrDtr(3)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rs232PortOutFlowType_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rs232PortTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  none(1), ctsRts(2), dsrDtr(3)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rs232PortOutFlowType_check_value( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortOutFlowType_val)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutFlowType_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rs232PortOutFlowType value.
     */

    return MFD_SUCCESS; /* rs232PortOutFlowType value not illegal */
} /* rs232PortOutFlowType_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rs232PortTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rs232PortTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rs232PortOutFlowType_undo_setup( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutFlowType_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rs232PortOutFlowType undo.
     */
    /*
     * copy rs232PortOutFlowType data
     * set rowreq_ctx->undo->rs232PortOutFlowType from rowreq_ctx->data.rs232PortOutFlowType
     */
    rowreq_ctx->undo->rs232PortOutFlowType = rowreq_ctx->data.rs232PortOutFlowType;


    return MFD_SUCCESS;
} /* rs232PortOutFlowType_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rs232PortOutFlowType_val
 *        A long containing the new value.
 */
int
rs232PortOutFlowType_set( rs232PortTable_rowreq_ctx *rowreq_ctx, u_long rs232PortOutFlowType_val )
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutFlowType_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rs232PortOutFlowType value.
     * set rs232PortOutFlowType value in rowreq_ctx->data
     */
    rowreq_ctx->data.rs232PortOutFlowType = rs232PortOutFlowType_val;

    return MFD_SUCCESS;
} /* rs232PortOutFlowType_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rs232PortOutFlowType_undo( rs232PortTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortOutFlowType_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rs232PortOutFlowType undo.
     */
    /*
     * copy rs232PortOutFlowType data
     * set rowreq_ctx->data.rs232PortOutFlowType from rowreq_ctx->undo->rs232PortOutFlowType
     */
    rowreq_ctx->data.rs232PortOutFlowType = rowreq_ctx->undo->rs232PortOutFlowType;

    
    return MFD_SUCCESS;
} /* rs232PortOutFlowType_undo */

/** @} */
