/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef RS232PORTTABLE_OIDS_H
#define RS232PORTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table rs232PortTable */
#define RS232PORTTABLE_OID              1,3,6,1,2,1,10,33,2


#define COLUMN_RS232PORTINDEX         1
    
#define COLUMN_RS232PORTTYPE         2
    
#define COLUMN_RS232PORTINSIGNUMBER         3
    
#define COLUMN_RS232PORTOUTSIGNUMBER         4
    
#define COLUMN_RS232PORTINSPEED         5
#define COLUMN_RS232PORTINSPEED_FLAG    (0x1 << 0)
    
#define COLUMN_RS232PORTOUTSPEED         6
#define COLUMN_RS232PORTOUTSPEED_FLAG    (0x1 << 1)
    
#define COLUMN_RS232PORTINFLOWTYPE         7
#define COLUMN_RS232PORTINFLOWTYPE_FLAG    (0x1 << 2)
    
#define COLUMN_RS232PORTOUTFLOWTYPE         8
#define COLUMN_RS232PORTOUTFLOWTYPE_FLAG    (0x1 << 3)
    

#define RS232PORTTABLE_MIN_COL   COLUMN_RS232PORTINDEX
#define RS232PORTTABLE_MAX_COL   COLUMN_RS232PORTOUTFLOWTYPE
    

    /*
     * TODO:405:r: Review RS232PORTTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define RS232PORTTABLE_SETTABLE_COLS (COLUMN_RS232PORTINSPEED_FLAG | COLUMN_RS232PORTOUTSPEED_FLAG | COLUMN_RS232PORTINFLOWTYPE_FLAG | COLUMN_RS232PORTOUTFLOWTYPE_FLAG)

#ifdef __cplusplus
}
#endif

#endif /* RS232PORTTABLE_OIDS_H */
