/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef RS232PORTTABLE_ENUMS_H
#define RS232PORTTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table rs232PortTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * rs232PortType (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RS232PORTTYPE_ENUMS
#define RS232PORTTYPE_ENUMS

#define RS232PORTTYPE_OTHER  1 
#define RS232PORTTYPE_RS232  2 
#define RS232PORTTYPE_RS422  3 
#define RS232PORTTYPE_RS423  4 
#define RS232PORTTYPE_V35  5 
#define RS232PORTTYPE_X21  6 

#endif /* RS232PORTTYPE_ENUMS */

//rachel
/*************************************************************
 * constants for enums for the MIB node
 * rs232PortInSpeed (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RS232PORTINSPEED_ENUMS
#define RS232PORTINSPEED_ENUMS

#define RS232PORTINSPEED_BD300     300
#define RS232PORTINSPEED_BD600     600
#define RS232PORTINSPEED_BD1200    1200
#define RS232PORTINSPEED_BD2400    2400
#define RS232PORTINSPEED_BD4800    4800
#define RS232PORTINSPEED_BD9600    9600
#define RS232PORTINSPEED_BD19200   19200
#define RS232PORTINSPEED_BD38400   38400
#define RS232PORTINSPEED_BD57600   57600
#define RS232PORTINSPEED_BD115200  115200
#define RS232PORTINSPEED_BD230400  230400

#endif /* RS232PORTINSPEED_ENUMS */

/*************************************************************
 * constants for enums for the MIB node
 * rs232PortOutSpeed (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RS232PORTOUTSPEED_ENUMS
#define RS232PORTOUTSPEED_ENUMS

#define RS232PORTOUTSPEED_BD300     300
#define RS232PORTOUTSPEED_BD600     600
#define RS232PORTOUTSPEED_BD1200    1200
#define RS232PORTOUTSPEED_BD2400    2400
#define RS232PORTOUTSPEED_BD4800    4800
#define RS232PORTOUTSPEED_BD9600    9600
#define RS232PORTOUTSPEED_BD19200   19200
#define RS232PORTOUTSPEED_BD38400   38400
#define RS232PORTOUTSPEED_BD57600   57600
#define RS232PORTOUTSPEED_BD115200  115200
#define RS232PORTOUTSPEED_BD230400  230400

#endif /* RS232PORTOUTSPEED */
//rachel


/*************************************************************
 * constants for enums for the MIB node
 * rs232PortInFlowType (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RS232PORTINFLOWTYPE_ENUMS
#define RS232PORTINFLOWTYPE_ENUMS

#define RS232PORTINFLOWTYPE_NONE  1 
#define RS232PORTINFLOWTYPE_CTSRTS  2

#endif /* RS232PORTINFLOWTYPE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * rs232PortOutFlowType (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef RS232PORTOUTFLOWTYPE_ENUMS
#define RS232PORTOUTFLOWTYPE_ENUMS

#define RS232PORTOUTFLOWTYPE_NONE  1 
#define RS232PORTOUTFLOWTYPE_CTSRTS  2 

#endif /* RS232PORTOUTFLOWTYPE_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* RS232PORTTABLE_ENUMS_H */
