/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "rs232PortTable.h"


#include "rs232PortTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232PortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232PortTable is subid 2 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.2, length: 9
*/

/**
 * initialization for rs232PortTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param rs232PortTable_reg
 *        Pointer to rs232PortTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
rs232PortTable_init_data(rs232PortTable_registration * rs232PortTable_reg)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize rs232PortTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* rs232PortTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
rs232PortTable_container_init(netsnmp_container **container_ptr_ptr)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to rs232PortTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

} /* rs232PortTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before rs232PortTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
rs232PortTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to rs232PortTable_container_shutdown\n");
        return;
    }

} /* rs232PortTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement rs232PortTable data load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  rs232PortTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
rs232PortTable_container_load(netsnmp_container *container)
{
    //rachel
    rs232PortTable_rowreq_ctx *rowreq_ctx;

    long   rs232PortIndex;

    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_container_load","called\n"));

    for (rs232PortIndex=1; rs232PortIndex < 5; rs232PortIndex++)
    {
        rowreq_ctx = rs232PortTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != rs232PortTable_indexes_set(rowreq_ctx, rs232PortIndex)) 
        {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "rs232PortTable data.\n");
            rs232PortTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /*
         * populate data context: 
         */
        rowreq_ctx->data.rs232PortInSpeed = RS232PORTINSPEED_BD19200;
        rowreq_ctx->data.rs232PortOutSpeed = RS232PORTOUTSPEED_BD19200;
        rowreq_ctx->data.rs232PortInFlowType = RS232PORTINFLOWTYPE_NONE;
        rowreq_ctx->data.rs232PortOutFlowType = RS232PORTOUTFLOWTYPE_NONE;

        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
    }

    DEBUGMSGT(("verbose:rs232PortTable:rs232PortTable_container_load",
               "inserted %d records\n", rs232PortIndex));

    return MFD_SUCCESS;
    //rachel
} /* rs232PortTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
rs232PortTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_container_free","called\n"));

    /*
     * TODO:380:M: Free rs232PortTable container data.
     */
} /* rs232PortTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
rs232PortTable_row_prep( rs232PortTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rs232PortTable:rs232PortTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* rs232PortTable_row_prep */

/** @} */
