/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file rs232AsyncPortTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef RS232ASYNCPORTTABLE_DATA_GET_H
#define RS232ASYNCPORTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232AsyncPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232AsyncPortTable is subid 3 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.3, length: 9
*/
    /*
     * indexes
     */

    int rs232AsyncPortBits_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, long * rs232AsyncPortBits_val_ptr );
    int rs232AsyncPortStopBits_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortStopBits_val_ptr );
    int rs232AsyncPortParity_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortParity_val_ptr );
    int rs232AsyncPortAutobaud_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortAutobaud_val_ptr );
    int rs232AsyncPortParityErrs_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortParityErrs_val_ptr );
    int rs232AsyncPortFramingErrs_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortFramingErrs_val_ptr );
    int rs232AsyncPortOverrunErrs_get( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long * rs232AsyncPortOverrunErrs_val_ptr );


int rs232AsyncPortTable_indexes_set_tbl_idx(rs232AsyncPortTable_mib_index *tbl_idx, long rs232AsyncPortIndex_val);
int rs232AsyncPortTable_indexes_set(rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, long rs232AsyncPortIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* RS232ASYNCPORTTABLE_DATA_GET_H */
/** @} */
