/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef RS232ASYNCPORTTABLE_H
#define RS232ASYNCPORTTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(RS-232-MIB)
config_require(RS-232-MIB/rs232AsyncPortTable/rs232AsyncPortTable_interface)
config_require(RS-232-MIB/rs232AsyncPortTable/rs232AsyncPortTable_data_access)
config_require(RS-232-MIB/rs232AsyncPortTable/rs232AsyncPortTable_data_get)
config_require(RS-232-MIB/rs232AsyncPortTable/rs232AsyncPortTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for rs232AsyncPortTable */
#include "rs232AsyncPortTable_oids.h"

/* enum definions */
#include "rs232AsyncPortTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_rs232AsyncPortTable(void);
void shutdown_rs232AsyncPortTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232AsyncPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232AsyncPortTable is subid 3 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.3, length: 9
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review rs232AsyncPortTable registration context.
     */
typedef netsnmp_data_list rs232AsyncPortTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review rs232AsyncPortTable data context structure.
 * This structure is used to represent the data for rs232AsyncPortTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * rs232AsyncPortTable.
 */
typedef struct rs232AsyncPortTable_data_s {
    
        /*
         * rs232AsyncPortBits(2)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
         */
   long   rs232AsyncPortBits;
    
        /*
         * rs232AsyncPortStopBits(3)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   rs232AsyncPortStopBits;
    
        /*
         * rs232AsyncPortParity(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   rs232AsyncPortParity;
    
        /*
         * rs232AsyncPortAutobaud(5)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   rs232AsyncPortAutobaud;
    
        /*
         * rs232AsyncPortParityErrs(6)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
   u_long   rs232AsyncPortParityErrs;
    
        /*
         * rs232AsyncPortFramingErrs(7)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
   u_long   rs232AsyncPortFramingErrs;
    
        /*
         * rs232AsyncPortOverrunErrs(8)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
         */
   u_long   rs232AsyncPortOverrunErrs;
    
} rs232AsyncPortTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review rs232AsyncPortTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef rs232AsyncPortTable_data rs232AsyncPortTable_undo_data;

/*
 * TODO:120:r: |-> Review rs232AsyncPortTable mib index.
 * This structure is used to represent the index for rs232AsyncPortTable.
 */
typedef struct rs232AsyncPortTable_mib_index_s {

        /*
         * rs232AsyncPortIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/A/w/e/R/d/H
         */
   long   rs232AsyncPortIndex;


} rs232AsyncPortTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review rs232AsyncPortTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_rs232AsyncPortTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review rs232AsyncPortTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * rs232AsyncPortTable_rowreq_ctx pointer.
 */
typedef struct rs232AsyncPortTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_rs232AsyncPortTable_IDX_LEN];
    
    rs232AsyncPortTable_mib_index        tbl_idx;
    
    rs232AsyncPortTable_data              data;
    rs232AsyncPortTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to rs232AsyncPortTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *rs232AsyncPortTable_data_list;

} rs232AsyncPortTable_rowreq_ctx;

typedef struct rs232AsyncPortTable_ref_rowreq_ctx_s {
    rs232AsyncPortTable_rowreq_ctx *rowreq_ctx;
} rs232AsyncPortTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int rs232AsyncPortTable_pre_request(rs232AsyncPortTable_registration * user_context);
    int rs232AsyncPortTable_post_request(rs232AsyncPortTable_registration * user_context,
        int rc);

    int rs232AsyncPortTable_rowreq_ctx_init(rs232AsyncPortTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void rs232AsyncPortTable_rowreq_ctx_cleanup(rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);

    int rs232AsyncPortTable_commit(rs232AsyncPortTable_rowreq_ctx * rowreq_ctx);

    rs232AsyncPortTable_rowreq_ctx *
                  rs232AsyncPortTable_row_find_by_mib_index(rs232AsyncPortTable_mib_index *mib_idx);

extern const oid rs232AsyncPortTable_oid[];
extern const int rs232AsyncPortTable_oid_size;


#include "rs232AsyncPortTable_interface.h"
#include "rs232AsyncPortTable_data_access.h"
#include "rs232AsyncPortTable_data_get.h"
#include "rs232AsyncPortTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* RS232ASYNCPORTTABLE_H */
/** @} */
