/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef RS232ASYNCPORTTABLE_DATA_SET_H
#define RS232ASYNCPORTTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rs232AsyncPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * RS-232-MIB::rs232AsyncPortTable is subid 3 of rs232.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.10.33.3, length: 9
*/


int rs232AsyncPortTable_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);
int rs232AsyncPortTable_undo_cleanup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);
int rs232AsyncPortTable_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);
int rs232AsyncPortTable_commit( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);
int rs232AsyncPortTable_undo_commit( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx);


int rs232AsyncPortBits_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, long rs232AsyncPortBits_val);
int rs232AsyncPortBits_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortBits_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, long rs232AsyncPortBits_val );
int rs232AsyncPortBits_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortStopBits_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortStopBits_val);
int rs232AsyncPortStopBits_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortStopBits_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortStopBits_val );
int rs232AsyncPortStopBits_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortParity_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortParity_val);
int rs232AsyncPortParity_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortParity_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortParity_val );
int rs232AsyncPortParity_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortAutobaud_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortAutobaud_val);
int rs232AsyncPortAutobaud_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortAutobaud_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortAutobaud_val );
int rs232AsyncPortAutobaud_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortParityErrs_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortParityErrs_val);
int rs232AsyncPortParityErrs_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortParityErrs_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortParityErrs_val );
int rs232AsyncPortParityErrs_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortFramingErrs_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortFramingErrs_val);
int rs232AsyncPortFramingErrs_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortFramingErrs_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortFramingErrs_val );
int rs232AsyncPortFramingErrs_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );

int rs232AsyncPortOverrunErrs_check_value( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortOverrunErrs_val);
int rs232AsyncPortOverrunErrs_undo_setup( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );
int rs232AsyncPortOverrunErrs_set( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx, u_long rs232AsyncPortOverrunErrs_val );
int rs232AsyncPortOverrunErrs_undo( rs232AsyncPortTable_rowreq_ctx *rowreq_ctx );


int rs232AsyncPortTable_check_dependencies(rs232AsyncPortTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* RS232ASYNCPORTTABLE_DATA_SET_H */
