/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef RS232NUMBER_H
#define RS232NUMBER_H

/* function declarations */
void init_rs232Number(void);

#endif /* RS232NUMBER_H */
